const ARTICLES = 'ARTICLES'
const LOADING = 'LOADING'
const END_LOADING = 'END-LOADING'
const ERROR = 'ERROR'
const ARTICLES_SLUG = 'ARTICLES-SLUG'
const REGISTRATION = 'REGISTRATION'
const AUTHORIZATION = 'AUTHORIZATION'
const UPDATE_PROFILE = 'UPDATE-PROFILE'
const LOG_OUT = 'LOG-OUT'
const DELETE_ARTICLE = 'DELETE-ARTICLE'
export {
  ARTICLES,
  ERROR,
  LOADING,
  END_LOADING,
  ARTICLES_SLUG,
  AUTHORIZATION,
  REGISTRATION,
  UPDATE_PROFILE,
  LOG_OUT,
  DELETE_ARTICLE,
}
